### ISSUE TITLE
在首页界面(非新闻页面),新闻列表无法点击

### ISSUE THREAD

**Issue by Weststreet** [zibuyuqing/UCBrowser#3]
在首页界面(非新闻页面),新闻列表无法点击（新闻列表用的RecyclerView，里面的item点击事件不响应），请问这个问题如何解决呢 感谢

![qq20180115-120957](https://user-images.githubusercontent.com/11329810/34926876-57c05e4a-f9ed-11e7-8496-dd09d7a94ff1.png)

**Comment by zibuyuqing** [comment]
![screenshot_2018-01-15-13-42-05-398_com zibuyuqing](https://user-images.githubusercontent.com/11385316/34928659-0f4aa6ae-f9fa-11e7-9717-9bb21d845ec8.png)
您好，这个我弄出来是正常的呀，你是添加额外的事件处理了吗？

**Comment by Weststreet** [comment]
多谢回复，刚刚发现代码里做了消息拦截 太不好意思了哈
